### ISSUE TITLE
Report function always throws error.

### ISSUE THREAD

**Issue by darphi** [joomla/jed-issues#14] opened 2017-07-06 11:49 UTC
In the extensions section, I click on the Report button and get the following error:

Could not load form com_jed.extension.

**Comment by acs-ferreira** [comment] 2017-07-07 16:13
Same here.

**Comment by sanderpotjer** [comment] 2017-07-08 11:48
Also for the password reset steps, like https://extensions.joomla.org/component/users/?view=login&Itemid=133 (if the &Itemid=133 is removed from the url, the process works).

**Comment by anibalsanchez** [comment] 2017-07-08 21:03
After the upgrade to Joomla 3.7.2, some links with no Itemid are wrongly redirected to the home page. 

To fix them, we are checking each one of them to assign an Itemid.

**Comment by anibalsanchez** [comment] 2017-07-09 08:52
For the record, Joomla 3.7.2 changed how the links with no Itemid behave... com_jed router doesn't  like to receive links with no Itemid.... so we have to review all links to assign the right Itemid.

In the case of JED login and registration, it's created with a custom registration in com_jed ... and the core stuff. To fix it, I have customised several modules and overrides, mainly with the idea of cleaning the non-standard stuff as much as possible.

To sum up, now we have:

- Com_jed login and registration (index.php?option=com_jed&view=profile&layout=edit&Itemid=149)
- "Login Links - Guest" - Custom html module to show JED registration and login
- "SCLogin - Registered Logout" - Legacy module to show the logout links
- Several Hidden menu items to define the right menu items
- com_users/login view overrides to guide the user to the Com_jed registration

Please, confirm if the issue is fixed now, or detail the exact steps to reproduce it.

**Comment by rs-123** [comment] 2017-07-11 12:32
Hi, 

When I`m trying to report: 

" An error has occurred while processing your request. It happens to the best of us!

Don't worry! There are no bugs without a fix!

If difficulties persist, please contact the System Administrator of this site and report the error below.

Could not load form com_jed.extension "

**Comment by jomres** [comment] 2017-07-14 09:15
I get the same thing, tried to report a malicious review and boom. Fails in both FF and Chrome.

**Comment by anibalsanchez** [comment] 2017-07-14 09:48
Hi,

Yesterday, we solved a critical server issue and now we are returning to the fix these remaining issues that were introduced in the update. 

Regards,

**Comment by anibalsanchez** [comment] 2017-07-19 14:26
Hi,

I've checked and solved the issue.

*After the update to Joomla 3.7.2, links with no Itemid and no matching menu item are reaching the wrong component and generating the 404 error.*

In this particular case, **the reports have been successfully received**, but com_jed failed to show the final message (redirecting to an article that was not defined in a menu item).

For the record, the solution has been to create a menu item for each one of these system articles.

Thanks for reporting!

**Closed by anibalsanchez** 2017-07-19 14:26 UTC
