### ISSUE TITLE
search results issue for "Install From Web" 

### ISSUE THREAD

**Issue by AlexRed** [joomla/jed-issues#5] opened 2017-03-31 10:30 UTC
from about 9 March 2017 is not possible to use the "**Install From Web**", message: 

> Cannot find any extensions for your version of Joomla. Please try a different search word or another category.

![install-issue](https://cloud.githubusercontent.com/assets/1362388/24546904/3579825c-1605-11e7-81b6-c72da46ba317.png)

Some day some category work, like: Extensions / Administration

Issue from: https://github.com/joomla-extensions/install-from-web-client/issues/42

**Comment by jeckodevelopment** [comment] 2017-03-31 17:43
According to the last Board Meeting report the IFW feature will be in offline mode soon.

> **4. Place Install from Web in an “offline” state due**
Proposed by Michael Babker, seconded by Rowan Hoskyns-Abrahall
_The motion passed with unanimous consent._

https://volunteers.joomla.org/board-of-directors/reports/480-osm-inc-full-board-meeting-march-30-2017

**Comment by mbabker** [comment] 2017-03-31 18:00
It still needs to be fixed.  The entire reason for that vote was to get consensus on putting it offline due to being busted.  If it's working, we can leave it up.

**Comment by beat** [comment] 2017-04-04 07:04
I second @mbabker : Install from Web is a major feature for Joomla, and any major issues, including the JED part need imho really to be fixed asap, and in all cases in time for Joomla 3.7.

**Comment by mbabker** [comment] 2017-04-06 01:34
This is an issue at the install from web server, not the JED.  I grabbed the URL the install from web server is querying for categories from https://github.com/joomla-extensions/install-from-web-server/blob/master/components/com_apps/models/category.php (assuming this repo actually has current code in it) and sent a request to https://extensions.joomla.org/index.php?option=com_jed&controller=filter&view=extension&format=json&limit=8&limitstart=0&filter[approved]=1&filter[published]=1&filter[core_catid]=16&extend=0&order=core_title&dir=ASC and got results.  That category is the [Ads & Affiliates](https://extensions.joomla.org/category/ads-a-affiliates/) category.  Checking that category on my company's site which has the client installed, that category is giving a "Cannot find any extensions for your version of Joomla. Please try a different search word or another category." result.  It serves results (I'm curious why the response from JED is sent with a `text/html` Content-Type header versus a JSON type though).  The "cannot find extensions" message is rendered by the install from web server if the extensions array is empty.

So, someone with admin access on the install from web server needs to get in and debug this connection issue.  Is the server failing to query the JED and using the cached data?  Is the model failing to handle the JED response correctly (could be indicative of the JSON payload changing)?

**Comment by jeckodevelopment** [comment] 2017-04-06 07:51
@JazParkyn / @anibalsanchez

**Comment by AlexRed** [comment] 2017-04-07 08:34
No one answers to mbabker :(
I think we can ask to Brad to add a new admin access on the install from web server and send it to mbabker

**Comment by anibalsanchez** [comment] 2017-04-07 08:54
I have no idea how IFW works. I have to check com_jed to review what's happened or what changed in the server.

**Comment by anibalsanchez** [comment] 2017-04-07 08:57
If you want to dig into com_jed, please, join us here: [Contributing Code to the JED](https://extensions.joomla.org/support/knowledgebase/item/contributing-code-to-the-jed/)

**Comment by anibalsanchez** [comment] 2017-04-07 09:24
Checking IFW.. it is calling https://appscdn.joomla.org/webapps (198.232.127.98)

- Example: https://appscdn.joomla.org/webapps/index.php?format=json&option=com_apps&view=dashboard&id=139&filter_search=notifications&product=Sm9vbWxhIQ==&release=My43&dev_level=MC1iZXRhNA==&list=grid&pv=MS4xLjA=&callback=jedapps_jsonpcallback

This server is not JED main site extensions.joomla.org (72.29.124.148).

A quick search in com_jed doesn't find any occurence of the JSONP callback jedapps_jsonpcallback.

So, I don't know what is com_apps.... I guess we need to access appscdn.joomla.org and check how the "webapp" is accesing JED db. It doesn't look like a call to the main site (com_jed).

**Comment by mbabker** [comment] 2017-04-07 12:27
The component in use can be found at https://github.com/joomla-extensions/install-from-web-server/tree/master/components/com_apps

The category and dashboard models look to be building a query to the same JED URLs.  With the dashboard model, https://github.com/joomla-extensions/install-from-web-server/blob/master/components/com_apps/models/dashboard.php#L223 is flooding the server's `error_log` file (I can get into the server's cPanel account) because a `foundintitle` property does not exist in each item apparently.

As I said in https://github.com/joomla/jed-issues/issues/5#issuecomment-292044216 the issue is purely at the install from web's server level.  At most, the involvement with the JED would be these two things:

- confirming if the JSON payload from the noted URL has changed in any way
- ensuring that route (and any other routes in com_jed returning a JSON payload) are using the correct `Content-Type` header

**Comment by beat** [comment] 2017-04-07 12:33
To understand what's goign on and debug com_jed, it's easy: Just checkout the git repository into a web subfolder, install the joomla, auto-discover the component, then change the URL in your joomla install-from-web plugin to point to your local com_apps install instead of the server one.

My free time today and this week-end is very limited, hopefully will have more next week, sorry.

**Comment by beat** [comment] 2017-04-07 12:39
install-from-web server (com_apps) has not changed in months/years, so the breaking change is not in com_apps, but most probably in the JSON side of JED.

Does JED team have a documentation of the recent changes in the JSON ?

**Comment by anibalsanchez** [comment] 2017-04-07 12:42
Hi,

We haven't changed this. I guess it was developed in that way when it was created.

If the IFW server was upgraded recently, it could have had this side-effect...

**Comment by mbabker** [comment] 2017-04-07 12:53
Sigh.

I'll fix it myself.

**Comment by beat** [comment] 2017-04-07 12:56
IFW server was not upgraded recently (appart regular Joomla security upgrades), so it's really strange. Only way to fix is hands-on, installing com_apps, pointing the install-from-web plugin to it, and starting the debug fun. Who knows, if nobody from install-from-web team jumps in, might find some time begin this week-end or of next week.

**Comment by anibalsanchez** [comment] 2017-04-07 13:01
Let me know if you need any change in com_jed.

If we need to change the content-type header, we have to check what it's going to be affected (there are angular apps and other Ajax calls that could be affected)

**Comment by mbabker** [comment] 2017-04-07 13:06
Well, there's no NEED to change it (most sources act based on the response data, really only browsers or systems with strict checks behave differently based on that header), but it is definitely incorrect that a JSON payload returns a `Content-Type: text/html` header.

**Comment by anibalsanchez** [comment] 2017-04-07 14:13
Yes, of course, it is wrong. No doubt on that. ... And, we could fill several pages about wrongs. 😁

**Comment by AlexRed** [comment] 2017-04-15 17:43
Hello to all,
any news about to fix the IFW server ?  Do you find the login credentials?

**Comment by mbabker** [comment] 2017-04-16 18:30
I looked yesterday, I could not reproduce any issues after cloning com_apps into the current CMS staging build.  I did find one case where a live 3.6.5 site pulling from the live IFW server was returning no result while the uncached local 3.7 install was working OK and after spending about 2 minutes looking at the model code I came to realize that the server is caching too much data (the full `JHttpResponse` object is being cached regardless of result, the response's body should be the only data cached and only on a successful HTTP query) and there is not adequate error checking in place.

I did take the liberty to "fix" the IFW server repo as noted in https://github.com/joomla-extensions/install-from-web-server/issues/10#issuecomment-294329198 and once @beat approves the new branch becoming the master branch it will be easier to go forward and optimize the IFW server component.

**Comment by AlexRed** [comment] 2017-04-17 04:47
And if the problem is from the update to Joomla 3.6.3 for the IFW server?
In version 3.6.3, the Joomla core started to report more errors if the data is stored incorrectly. Now if the JSON syntax is broken, the error is triggered, before 3.6.3 no.
Maybe some extensions have issue in the data, within its own parameters data sheet in the database.
{""} need to be now {\"\"}

This would explain why some category works and some not. The category which contains the extension with wrong data format not work, other category are ok.

We can try to examine the database to look through the "params" column for potential issues.

**Comment by mbabker** [comment] 2017-04-17 11:04
It has nothing to do with broken JSON.

**Comment by anibalsanchez** [comment] 2017-06-09 10:05
Hi @AlexRed 

IFW seems to be working fine now. I'm closing the issue. 

Please, let us know if the issue remains and how to reproduce it.

**Closed by anibalsanchez** 2017-06-09 10:05 UTC
