### ISSUE TITLE
No subcategories in Extensions Specific

### ISSUE THREAD

**Issue by Sulpher** [joomla/jed-issues#25] opened 2017-10-22 10:04 UTC
If we go to https://extensions.joomla.org/ we are not able to find a list of subcategories in Extensions Specific category. So, users usually are looking for add-ons of specific extension and need a choice. That's very important UX issue.

![screen shot 2017-10-22 at 13 01 56](https://user-images.githubusercontent.com/3432048/31860804-4961de52-b729-11e7-8f32-0370f774e523.png)

**Comment by dam-man** [comment] 2017-10-29 09:01
Where is the code so people can help development..

**Comment by wilsonge** [comment] 2017-10-29 19:57
It's in a private repo. There's a Contributor Agreement you have to sign to get access. All the information can be found on the contributing to JED page https://extensions.joomla.org/support/knowledgebase/item/contributing-code-to-the-jed/

**Comment by anibalsanchez** [comment] 2018-02-16 10:00
Hi,

Extension Specific has a very long list of subcategories. So, it doesn't fit in the same category organization as the rest of the tree. This tree definition was done in this way mainly because the tree was never fully visualized.

Reorganizing the tree is a whole different conversation.

So, it is not a bug, and it is working as expected. Closing the ticket. Thanks for reporting!

**Closed by anibalsanchez** 2018-02-16 10:00 UTC

**Comment by Sulpher** [comment] 2018-02-16 10:22
Hi Anibal,
This is really sad news... Let me explain why it is important. As a user, I would like to see all add-ons for the specific extension. I did it much time in the past. Let it be Virtuemart for example. It is very useful to examine the subcategory and find new add-ons to extend the site. 
A big flat list as in previous JED version could help...
But ok, the idea is declined. 
Thanks for the reply and have a nice day!

**Comment by anibalsanchez** [comment] 2018-02-16 10:41
I've just opened an issue to implement this functionality. Please, follow this ticket https://github.com/joomla/jed-issues/issues/34

Txs
