### ISSUE TITLE
Lots of pages are blank

### ISSUE THREAD

**Issue by GeraintEdwards** [joomla/jed-issues#236] opened 2021-12-02 09:35 UTC
**ATTENTION: If you have a question or you need to contact the JED Team about an Extension, please, contact us via the JED Ticketing System: https://extensions.joomla.org/profile/** 

**Describe the bug**

Many pages on JED are blank today e.g. https://extensions.joomla.org/extension/calendars-a-events/events/jevents/ or https://extensions.joomla.org/category/e-commerce/shopping-cart/

**To Reproduce**
Visit the links above.

**Comment by anibalsanchez** [comment] 2021-12-02 10:25
I've reported the issue also to the webmaster's team: https://github.com/joomla/joomla-websites/issues/1693

**Comment by Llewellynvdm** [comment] 2021-12-02 11:30
Thank you for reporting this issue, we are investigating it...

**Comment by Llewellynvdm** [comment] 2021-12-02 12:09
So at this point the only issue I found was old cronjobs on the old server, these I have now removed (they where calling the same systems). All pages seems to now load correctly. I am not seeing any errors in the Normal Joomla Error logs...

Will continue to keep an eye on things.... but the pages mentioned in this post seems to be up again and working as expected. I will therefore close this issue.... should you have more feedback please comment on this https://github.com/joomla/joomla-websites/issues/1693 opened by Anibal.

**Comment by GeraintEdwards** [comment] 2021-12-02 12:23
Thanks for your help on this one! On 2 Dec 2021 12:09, "<<ewe>>yn" ***@***.***> wrote:
So at this point the only issue I found was old cronjobs on the old server, these I have now removed (they where calling the same systems). All pages seems to now load correctly. I am not seeing any errors in the Normal Joomla Error logs...
Will continue to keep an eye on things.... but the pages mentioned in this post seems to be up again and working as expected. I will therefore close this issue.... should you have more feedback please comment on this joomla/joomla-websites#1693 opened by Anibal.

**Comment by hvdmeer** [comment] 2021-12-09 08:08
I received a report via our Twitter account that JED still is having issues and serving blank pages. Should I create a new issue or can this one be opened again?

Original tweet: https://twitter.com/HidetoOshima/status/1468814876131102723
For example extension page not opening: https://extensions.joomla.org/extension/style-a-design/modules-management/advanced-module-manager/

**Comment by anibalsanchez** [comment] 2021-12-09 08:51
@Llewellynvdm Confirmed. There are still blank pages.

**Comment by Llewellynvdm** [comment] 2021-12-09 22:15
We are having issues with the image cashing system of Fabric (custom build) for JED3 (the current JED). While we are trying to make sure that the site remains stable, we find that at times the memory footprint goes ballistic... we are stuck on PHP 7.2 and much more pain... While we are working on the JED4 the issue continues...

So yet again we have increased the memory and other tweaks, and it seems to over some kind of improvement. But the real fix would be to go into the actual Fabric extension and fix a number of issues. Those who build the current JED3 are no longer with the project. I am planning to run the maze somewhere over the holidays... any who would like to join me, just give me a bump so I can collaborate our efforts.

**Closed as completed** 2021-12-09 22:16 UTC
