### ISSUE TITLE
search not work in extensions.joomla.org

### ISSUE THREAD

**Issue by sabersaberi2** [joomla/jed-issues#205] opened 2020-07-14 14:57 UTC
hi. 
you can test that search box on the menu not work.any word that you search return empty result.

**Comment by anibalsanchez** [comment] 2020-11-22 14:58
It is working fine on my side. Please, check if you have some browser console errors or more information about how to reproduce the issue. Test with other browsers on a different connection to verify if it is an issue on your side.

**Comment by anibalsanchez** [comment] 2021-01-23 14:38
No answer since Nov 2020. Closing the ticket.

**Closed as completed by anibalsanchez** 2021-01-23 14:38 UTC
