### ISSUE TITLE
Newly submitted extension disappeared from profile page after it was published

### ISSUE THREAD

**Issue by glOOmyART** [joomla/jed-issues#61] opened 2018-11-13 19:11 UTC
Around 2-3 weeks ago I submitted an extension to the JED.  
For as long as it awaited approval it was listed in my profile's extension tab.  
As soon as the extension was publicly listed in the JED it disappeared from my profile.

Furthermore, the extension has the wrong developer linked. If you click on the developer it says 

> Error, Not Found

Also, as long as i'm logged in to the JED, the extension page says 

> No extensions found

When I logout, i can view the extension!

The support is horrible!! I opened a ticket a week ago and there is no response!

**Comment by anibalsanchez** [comment] 2018-11-13 19:23
Hi, Thanks for reaching out!

We are processing the queue in the fastest possible that volunteers can answer.

Every extension must be checked, replied and followed until it is finally published or rejected.

We start the process with a simple name check (where many developers fail to name the JED entry like the installed extension) and we follow with several iterations on JED Checker output https://extensions.joomla.org/extension/jedchecker/. Finally, if we find discrepancies, we have to read the source code.

Overall, the whole process takes time. In order to better assist you, please do not submit multiple tickets per issue. Duplicate requests will slow down response time and may delay resolution. We recommend that you do not update tickets unless it is absolutely necessary. Updated tickets are automatically sent to the end of the processing queue.

Best Regards

**Comment by glOOmyART** [comment] 2018-11-14 16:09
Thank for clearing the ticket flow!

I know that the extensions are checked manually, which I totally understand and consent with since it improves security.  
But i'm actually more concerned about the potential bug in the system when uploaded extensions might disappear from the uploader's backend.  
Unless I was the only one who was affected.

**Comment by anibalsanchez** [comment] 2018-11-14 16:22
Tomorrow, I have a very long journey traveling, so the plan is checking all tickets ;-)

**Comment by Yagnenok** [comment] 2018-11-20 09:48
> Unless I was the only one who was affected.
You are not alone ) all new submitted extensions are "developed" as unknown KLG. My also

**Comment by anibalsanchez** [comment] 2018-11-20 11:13
Not all the new submitted extensions. We have detected and confirmed the inconsistency in some cases and we are investigating the issue.

**Comment by anibalsanchez** [comment] 2018-12-02 20:02
We have fixed the inconsistency the extension assignation issue. Now, it is under control.

I'm closing the issue. Feel free to comment on the issue if it still persists in the system. I'm keeping an eye on the topic.

**Comment by logeecom** [comment] 2019-01-09 16:07
Hi @anibalsanchez, I am experiencing the same problem. Extension is submitted on December 27, and it immediately disappeared from my account. What is strange is that if I open extension's public page when I'm _not_ logged it, I can see it, but when I am logged in, I don't see neither the page nor extension in my account. can you please confirm this? Extension key is `cleverreach-newsletter-marketing-extension`. Thanks.

**Comment by anibalsanchez** [comment] 2019-01-09 16:19
Hi,

In the previous cases, the issue was to be related to the definition of the Developer User profile before the extension submission. The system is accepting extensions before the Developer User profile creation. But, this should not be allowed.

The extension has been received. In the next extensions batch review, we are going to re-assign it and probably force the definition of the Developer User profile before the extension submission to avoid future reports/issues.

**Comment by logeecom** [comment] 2019-01-09 16:23
Hi, thanks for the quick reply! Does this means it will be connected to my account (`cleverreach`) once it is reviewed?

**Comment by anibalsanchez** [comment] 2019-01-09 16:56
Please, send us a ticket to review your case (New Listing Support).

BTW: An extension can't have "extension" in the name Ref: https://github.com/joomla/jed-issues/wiki/Extension-&-Ticket-Reply-Templates#reserved-words

**Comment by logeecom** [comment] 2019-01-09 16:58
If I need to submit it again because of the name, then I can do that and you can delete the old one, so I don't need to open another ticket, right?

**Comment by anibalsanchez** [comment] 2019-01-09 17:41
Yes, sure, send a new extension, with the corrected name. 

Remember to also check it with **JED Checker** https://extensions.joomla.org/extension/jedchecker/

**Comment by anibalsanchez** [comment] 2019-01-10 18:48
Since it is back under control, I'm closing it again.

**Closed by anibalsanchez** 2019-01-10 18:48 UTC
Labels: user-management
