### ISSUE TITLE
Free Listings: missing "Value for money" causing lower score

### ISSUE THREAD

**Issue by BennyTheDev** [joomla/jed-issues#177] opened 2020-05-31 09:15 UTC
**Describe the bug**
A user of mine tried to leave a review for one of my free listings and reported back that despite giving it good ratings, the overall score has been too low (expected 99%, returned 76%).

He then checked his review and noticed that the "Money for Value" option is displayed as "-1" although it shouldn't be available for free listings and the score was showing "76%" instead of the expected "99%".

I cannot tell at this point if this is a display bug or if it really adds up to the overall calculation to sort extensions, but it is worth reporting and investigating because it confuses the reviewer, and if it adds to the sorting, it gives a disdvantage over paid listings.

**To Reproduce**
1. Go to the JED and leave a review for a free listing
2. Wait for the approval and look at the overall score under your reviews, it will show "Value for Money" with a "-1" value and a lower score that you'd expect.

**Expected behavior**
Since the "Value for Money" option isn't included for free listing, its missing score shouldn't be displayed and also not count in the overall calculation.

**Screenshots**
<img width="510" alt="free-review" src="https://user-images.githubusercontent.com/1433403/83348703-30753700-a32f-11ea-9894-f802a7960512.png">

**Comment by anibalsanchez** [comment] 2020-06-06 18:51
It looks like it is a very specific case. What extension are you checking

This is a similar review (Akeeba), that doesn't have the -1 in the review.

![case2](https://user-images.githubusercontent.com/385780/83952213-89fdca00-a837-11ea-8714-cfc28cb81f4b.png)

**Comment by anibalsanchez** [comment] 2020-06-13 07:49
Please, send us more info to reproduce the issue. 

I'm closing the issue, please, re-open with more info.

**Closed as completed by anibalsanchez** 2020-06-13 07:49 UTC
